import type { NextPage } from "next";
import Head from "next/head";
import Canvas from "../components/Canvas";
import { initGame, start } from "../game";

const Home: NextPage = () => {
  // const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
  const handleStartGame = () => {
    initGame();
    start();
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Reverse TD
        </h1>
        <Canvas onContextLoaded={handleStartGame} />
      </main>
    </>
  );
};

export default Home;
